package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.input.MouseEvent;

public class acceder 1Controller {
	@FXML
	private TextField ingreseusuarioid;
	@FXML
	private PasswordField ingresecotraseñaid;
	@FXML
	private Label txtusuarioid;
	@FXML
	private Label txtcontraseñaid;
	@FXML
	private Button botoningresarid;

	// Event Listener on Button[#botoningresarid].onMouseClicked
	@FXML
	public void botoningresar(MouseEvent event) {
		// TODO Autogenerated
	}
}
