package vista;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class crear usuario 1Controller {
	@FXML
	private TextField crearuserid;
	@FXML
	private Label txtconfirmepassword;
	@FXML
	private TextField crearpasswordid;
	@FXML
	private TextField confirmepasswordid;

	// Event Listener on Button.onMouseClicked
	@FXML
	public void botonaccedercrearusuario(MouseEvent event) {
		// TODO Autogenerated
	}
}
