package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class LoginController {
	@FXML
	private Label bienvenidooid;
	@FXML
	private Button botonacceder;
	@FXML
	private Button botoncrearusuario;

	// Event Listener on Button[#botonacceder].onMouseClicked
	@FXML
	public void clickacceder(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#botoncrearusuario].onMouseClicked
	@FXML
	public void clickcrearusuario(MouseEvent event) {
		// TODO Autogenerated
	}
}
